recipe: default.v1
assistant_id: ferocious-parameter
language: es
pipeline:
- name: CompactLLMCommandGenerator
  prompt_template: "prompts/command_prompt.jinja2"
  llm:  
    model_group: self_hosted_llm
  flow_retrieval:
    embeddings:
      model_group: openai-embeddings
policies:
- name: FlowPolicy
- name: IntentlessPolicy
  llm:
    model_group: self_hosted_llm
  embeddings:
    model_group: openai-embeddings
