recipe: default.v1
assistant_id: ferocious-parameter
language: es
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 3
  max_ngram: 5
- name: LogisticRegressionClassifier
- name: FallbackClassifier
  threshold: 0.75
  ambiguity_threshold: 0.10
- name: NLUCommandAdapter
policies:
- name: FlowPolicy
